var l=function(b){var c=0;return function(){return c<b.length?{done:!1,value:b[c++]}:{done:!0}}},m=function(b){var c="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];return c?c.call(b):{next:l(b)}},n="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this,p="function"==typeof Object.defineProperties?Object.defineProperty:function(b,c,g){b!=Array.prototype&&b!=Object.prototype&&(b[c]=g.value)},q=function(b,c){if(c){var g=n;b=b.split(".");for(var f=
0;f<b.length-1;f++){var e=b[f];e in g||(g[e]={});g=g[e]}b=b[b.length-1];f=g[b];c=c(f);c!=f&&null!=c&&p(g,b,{configurable:!0,writable:!0,value:c})}};
q("Promise",function(b){function c(){this.a=null}function g(a){return a instanceof e?a:new e(function(d){d(a)})}if(b)return b;c.prototype.b=function(a){if(null==this.a){this.a=[];var d=this;this.c(function(){d.g()})}this.a.push(a)};var f=n.setTimeout;c.prototype.c=function(a){f(a,0)};c.prototype.g=function(){for(;this.a&&this.a.length;){var a=this.a;this.a=[];for(var d=0;d<a.length;++d){var b=a[d];a[d]=null;try{b()}catch(k){this.f(k)}}}this.a=null};c.prototype.f=function(a){this.c(function(){throw a;
})};var e=function(a){this.b=0;this.g=void 0;this.a=[];var d=this.c();try{a(d.resolve,d.reject)}catch(h){d.reject(h)}};e.prototype.c=function(){function a(a){return function(e){b||(b=!0,a.call(d,e))}}var d=this,b=!1;return{resolve:a(this.o),reject:a(this.f)}};e.prototype.o=function(a){if(a===this)this.f(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof e)this.s(a);else{a:switch(typeof a){case "object":var d=null!=a;break a;case "function":d=!0;break a;default:d=!1}d?this.m(a):
this.i(a)}};e.prototype.m=function(a){var d=void 0;try{d=a.then}catch(h){this.f(h);return}"function"==typeof d?this.u(d,a):this.i(a)};e.prototype.f=function(a){this.j(2,a)};e.prototype.i=function(a){this.j(1,a)};e.prototype.j=function(a,d){if(0!=this.b)throw Error("Cannot settle("+a+", "+d+"): Promise already settled in state"+this.b);this.b=a;this.g=d;this.l()};e.prototype.l=function(){if(null!=this.a){for(var a=0;a<this.a.length;++a)r.b(this.a[a]);this.a=null}};var r=new c;e.prototype.s=function(a){var d=
this.c();a.h(d.resolve,d.reject)};e.prototype.u=function(a,d){var b=this.c();try{a.call(d,b.resolve,b.reject)}catch(k){b.reject(k)}};e.prototype.then=function(a,b){function d(a,b){return"function"==typeof a?function(b){try{c(a(b))}catch(x){g(x)}}:b}var c,g,f=new e(function(a,b){c=a;g=b});this.h(d(a,c),d(b,g));return f};e.prototype.catch=function(a){return this.then(void 0,a)};e.prototype.h=function(a,b){function d(){switch(c.b){case 1:a(c.g);break;case 2:b(c.g);break;default:throw Error("Unexpected state: "+
c.b);}}var c=this;null==this.a?r.b(d):this.a.push(d)};e.resolve=g;e.reject=function(a){return new e(function(b,c){c(a)})};e.race=function(a){return new e(function(b,c){for(var d=m(a),e=d.next();!e.done;e=d.next())g(e.value).h(b,c)})};e.all=function(a){var b=m(a),c=b.next();return c.done?g([]):new e(function(a,d){function e(b){return function(c){f[b]=c;h--;0==h&&a(f)}}var f=[],h=0;do f.push(void 0),h++,g(c.value).h(e(f.length-1),d),c=b.next();while(!c.done)})};return e});
var t=this,u=/^[\w+/_-]+[=]{0,2}$/,v=null,w=function(){var b=t.document;return(b=b.querySelector&&b.querySelector("script[nonce]"))&&(b=b.nonce||b.getAttribute("nonce"))&&u.test(b)?b:""};function y(){window.performance.mark("gapi_load_end");window.performance.measure("gapi_load","gapi_load_start","gapi_load_end");z()}var z,A=null;
function B(){if(A)return A;window.performance.mark("gapi_load_start");var b=window.colabExperiments&&window.colabExperiments.first_party_auth;return A=new Promise(function(c,g){z=c;window.gapi_onload=function(){b?z():gapi.load("auth:client",y)};var f=document.createElement("script");f.src="https://apis.google.com/js/client.js";f.async=!0;null===v&&(v=w());(c=v)&&f.setAttribute("nonce",c);f.onerror=function(){g(Error("Error loading "+f.src))};c=document.getElementsByTagName("script")[0];c.parentNode.insertBefore(f,
c)})}window.colab_gapi_loader={};window.colab_gapi_loader.load=B;B().then(function(){},function(){});
